Algoritmo "calcula_area_circulo"
// Disciplina  :  Algoritmos
// Professor   : Lucas Nadalete
// Descrição   : Algoritimo que calcula a área de um circulo a partir de qualquer raio
// Autor(a)    : Ana Carolina Simplicio de Moura
// Data atual  : 03/09/2018
Var

 raio, areaCirculo : real
 
Inicio

 escreval ("Informe o raio do círculo:")
 leia(raio)
 
 areaCirculo <- 3.14 * (raio ^ 2)
 
 escreval("A área do círculo de raio: ", numpcarac(raio) , " é ", numpcarac(areaCirculo))

Fimalgoritmo